[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
async-graphql = "5.0.10"
async-graphql-axum = "5.0.10"
axum = { version = "0.6.18", features = ["tracing"] }
deadpool-postgres = "0.10.5"
dotenv = "0.15.0"
hyper = { version = "0.14.27", features = ["full"] }
serde = "1.0.170"
time = "0.3.23"
tokio = { version = "1.29.0", features = ["full"] }
tokio-postgres = { version = "0.7.8", features = ["with-time-0_3"] }
tower = "0.4.13"
tower-http = { version = "0.4.1", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
