[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
async-graphql = { version = "6.0.6", features = ["dataloader", "time"] }
async-graphql-axum = "6.0.6"
axum = { version = "0.6.20", features = ["http2", "tracing"] }
deadpool-postgres = "0.10.5"
dotenv = "0.15.0"
hyper = { version = "0.14.27", features = ["full"] }
serde = "1.0.188"
time = "0.3.28"
tokio = { version = "1.32.0", features = ["full"] }
tokio-postgres = { version = "0.7.10", features = ["with-time-0_3"] }
tower = "0.4.13"
tower-http = { version = "0.4.4", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
