name: "fakebook"

services:
  dev:
    image: "my-devcontainer"
    command: "sleep infinity"
    volumes:
      - "../..:/workspaces:cached"

  database:
    user: "postgres"
    image: "docker.io/library/postgres:16-alpine"
    command: "-c log_statement=all"
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes: ["database-volume:/var/lib/postgresql/data"]

  tracer:
    image: "quay.io/jaegertracing/all-in-one:latest"
    ports: ["16686:16686", "4317:4317", "4318:4318"]
    environment:
      COLLECTOR_OTLP_ENABLED: "true"

volumes:
  database-volume:
